# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
    groups:
      go-patch:
        update-types:
        - "patch"
      go-minor:
        update-types:
        - "minor"
      go-major:
        update-types:
        - "major"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /docs/plugins/gtag
    schedule:
      interval: daily
