# Documentation: https://github.com/BirthdayResearch/oss-governance-bot
on:
    pull_request_target:
      types: [ synchronize, opened, labeled, unlabeled ]
    issues:
      types: [ opened, labeled, unlabeled ]
    issue_comment:
      types: [ created ]

jobs:
    governance:
        name: Governance
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
              with:
                egress-policy: audit

            - uses: BirthdayResearch/oss-governance-bot@37c8583c6b8596d173b68ffaed543e2485f4f193 # v3.0.0
              with:
                config-path: .github/governance.yml
    